version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck: # Ensures RabbitMQ is fully operational before dependent services start.
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  producer:
    build: ./producer
    depends_on:
      rabbitmq:
        condition: service_healthy # Ensures producer doesn't try to connect to RabbitMQ before it's ready.

  consumer:
    build: ./consumer
    depends_on:
      rabbitmq:
        condition: service_healthy # Ensures the consumer doesn't try to connect to RabbitMQ before it's ready.
    